// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurfBookingSystem.Models;

#nullable disable

namespace TurfBookingSystem.Migrations
{
    [DbContext(typeof(TurfDbContext))]
    [Migration("20240708111420_TurfBookingSystem")]
    partial class TurfBookingSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TurfBookingSystem.Models.Turf", b =>
                {
                    b.Property<int>("TurfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TurfId"));

                    b.Property<int?>("Capacity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Games");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Location");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("TurfId");

                    b.ToTable("turf");
                });
#pragma warning restore 612, 618
        }
    }
}
